# Generated by Django 2.0.3 on 2018-03-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organization', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('github_username', models.CharField(blank=True, max_length=64, null=True)),
                ('picture_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField(choices=[(1, 'Question One'), (2, 'Question Two')])),
                ('project_demo_url', models.URLField()),
                ('project_source_url', models.URLField()),
                ('submition_screenshot', models.URLField()),
                ('short_description', models.CharField(max_length=256)),
                ('long_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='contest.Submission'),
        ),
    ]
