# Generated by Django 2.0.3 on 2018-04-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='picture_url',
            new_name='picture_link',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='project_demo_url',
            new_name='screenshot_link',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='project_source_url',
            new_name='source_code_link',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submition_screenshot',
            new_name='visualization_link',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.AddField(
            model_name='applicant',
            name='jobtitle',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
