# Generated by Django 2.0.3 on 2018-04-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20180426_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='github_username',
        ),
        migrations.AddField(
            model_name='applicant',
            name='github_user_page',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
