# Generated by Django 2.0.3 on 2018-04-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20180426_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='github_user_page',
            new_name='github_account',
        ),
    ]
