# Generated by Django 2.0.3 on 2018-04-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20180426_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='contest.Submission'),
        ),
    ]
