# Generated by Django 2.0.3 on 2018-05-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20180427_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
